export const MOSTRAR_PRODUCTOS = "MOSTRAR_PRODUCTOS";
export const MOSTRAR_PRODUCTO = "MOSTRAR_PRODUCTO";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const GUARDAR_PRODUCTO = "GUARDAR_PRODUCTO";
export const BUSCAR_PRODUCTO = "BUSCAR_PRODUCTO";
export const MODIFICAR_PRODUCTO = "MODIFICAR_PRODUCTO";
export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO";
